name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.5  # Change this based on your Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build -o app .

      - name: Install AWS CLI & EB CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo "$HOME/.local/bin:$HOME/.local/bin/aws" >> $GITHUB_PATH

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Test S3 Access
        run: aws s3 ls s3://elasticbeanstalk-ap-south-1-559050252448

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
          EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
        run: |
          eb init $EB_APP_NAME --platform "Go 1 running on 64bit Amazon Linux 2023" --region $AWS_REGION
          eb use $EB_ENV_NAME
          eb deploy
